Break up operations manual into topics files
mestekmachinery/Machine_Manuals pull request #13
Opened 2021-10-05 15:02 UTC by ajw1970

2021-10-05 15:04 UTC, ajw1970 commented
@briandominick , this is a smaller example that might be easier to discuss. 

all of these sub-topics would apply to either an engel or ipi branded coil line with the exception of hand-feeding-blanks.adoc which is currently brand specific to ipi.

2021-10-05 15:07 UTC, ajw1970 commented
Would this IPI027V02_PDoperation.adoc with the includes go away and be replaced with a _manifest file somewhere?

Would I then also need that introduction paragraph to be placed in an adoc file or would that type of thing go somewhere else?

2021-10-08 15:07 UTC, briandominick requested changes
Other than one note about header levels, this looks good.

To answer your questions:

> Would this IPI027V02_PDoperation.adoc with the includes go away and be replaced with a _manifest file somewhere?

Yes, we will generate these index files on the fly from a template drawing from each product's `_manifest.yml` file. This is a good model for now, though, so let's keep it.

> Would I then also need that introduction paragraph to be placed in an adoc file or would that type of thing go somewhere else?

We can include anything we want in the template that generates the `.adoc` files. But we'll also be able to use conditionals and variables, so we can source this stuff anywhere and transclude it on a per-product or per-volume basis.

2021-10-08 15:07 UTC, briandominick commented on ProFabriduct/Operation/e-stop-recovery.adoc
> +== Recovering from Emergency Shutdown
Best practice is to always start files with level 0 headers (1 `=` sign).

Then we adjust the level where we `include` the file. Consider that for web pages, we want level 0, and for chapters, we want level 1 (`==`), and sometimes a topic will get used in more than one place and might have a different contextual level. AsciiDoc offers `:leveloffset:` which can be `+1`, `+2`, or `-1`,  etc. So we set the starting level contextually at the point of publishing.

2021-10-08 17:37 UTC, merged